version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: devtools_redis
    ports:
      - "6379:6379"
    volumes:
      - D:\DevTools\Docker\volumes/redis:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
